### ISSUE TITLE
Not all proxies used

### ISSUE THREAD

**Issue by silentlmao** [suffz/Crumble#4]
Hey so this was actually a problem with the previous version as well, but it will load all proxies without using them all. And if I don't add a fix in the code it will actually use none of them. The only fix that I found was to add use_proxy++ below mfaamt++ and this then allows 1 proxy in use per account (still doesn't mean all of them are being used).

**Comment by suffz** [comment]
hm? afaik when i coded this i made it use the amt of proxys needed to cover the accounts, this can be changed in the config i believe.

"accounts_per_gc_proxy": 5,
for mfa it defaults to 1.

this also applies for authentication as 1 ip can auth 3 accounts at a time, and for the actual requests i default it to 5 gcs per proxy, this means if you have 20 gcs you only really need 4 proxys.

**Comment by suffz** [comment]
and, the amount of proxys assigned to an account group doesnt matter tbf, minecraft rate limits based on IP and bearer token, it would be pointless to use all the proxys and range through them for a few accounts, as you will still get 429s.

**Comment by silentlmao** [comment]
Yeah so is there no way to change the amount of proxys for mfas?

**Comment by suffz** [comment]
hm i can make it a feature if you want, but atm no.

**Comment by suffz** [comment]
all it will do is allow you to use multiple mfas per 1 proxy though.

**Comment by silentlmao** [comment]
sure yeah i think it would help me out a lot, thanks

**Comment by suffz** [comment]
mk sec.

**Comment by silentlmao** [comment]
i mean the main thing i have an issue with is why bother with buying 100 proxies or something from webshare and then not all of them go to use?

**Comment by suffz** [comment]
buy a custom amount based on your accounts, but its always good to have a few extra.

**Comment by silentlmao** [comment]
so like what is recommended if you have only 10 or less mfas, i thought that gcs dont give more requests anymore? i just dont really understand why utilizing more than less of your proxys isnt ideal for mfas?

**Comment by suffz** [comment]
implemented the config values and changes to the code, should be working.

**Comment by suffz** [comment]
if u have 10 mfas, u only really need - amt of proxys u want per IP / acc amt = proxys needed

20 mfas / 3 per ip = 7~ proxys

**Comment by silentlmao** [comment]
i see, but is there a difference with gcs other than being prename

**Comment by silentlmao** [comment]
anyway, thanks for the addition, do you have discord or anything if i have any other questions?

**Comment by suffz** [comment]
sadly not.
