### ISSUE TITLE
Some Runtime Panic Error

### ISSUE THREAD

**Issue by Disshi300** [suffz/Crumble#5]
![cmd_fWzvywDRQv](https://github.com/suffz/Crumble/assets/70773678/a01bed85-5ed8-4373-a212-a1a156ffb3c8)

This happens when I put the account in accounts.txt
email:pass format ofcourse
and i do go run main.go

**Comment by suffz** [comment]
do you have proxys?

**Comment by suffz** [comment]
the error originates from that function, it means it isnt detecting any proxys.

**Comment by Disshi300** [comment]
Im using proxyscrape's free http and socks5 proxies
Could that be the problem? If so where can I get decent free ones

**Comment by suffz** [comment]
what format are you using? ip:port / ip:port:user:pass?

**Comment by suffz** [comment]
> Im using proxyscrape's free http and socks5 proxies Could that be the problem? If so where can I get decent free ones

Webshare gives 10 for free, and if you edit the free subscription you should be able to change there location to US not sure though.

**Comment by Disshi300** [comment]
> what format are you using? ip:port or ip:port:user:pass?
I use IP:Port
I have like 940 proxies
I got it working tho
